### PR TITLE
Feature: React/hook form

### PR DESCRIPTION
**Pull request by demisgech**
Hey Gebreyohannis please review the changes that the use of react-hook-form as part of managing the form.

### CODE REVIEW

**Review by johngech — CHANGES_REQUESTED** [review]
Everything looks perfect please make changes and do another commit.

**Review by demisgech — COMMENTED** [review]
Alright everything is done.

**Review by demisgech — COMMENTED** [review]
Everything looks perfect, please make a commit.

**Review by johngech — COMMENTED** [review]
Everything looks perfect.

**Pull request merged**
